### ISSUE TITLE
Don't assume `black` is in PATH

### ISSUE THREAD

**Issue by aivarannamaa** [Franccisco/thonny-black-code-format#1]
I got an issue regarding this project in Thonny's issue tracker: https://github.com/thonny/thonny/issues/1016

It looks like the user doesn't have `black` in PATH. I recommend calling `<python> -m black` instead of the wrapper script `black`. In `thonny.running` there is function `get_interpreter_for_subprocess` which gives you the path to suitable interpreter.

**Comment by Franccisco** [comment]
Hey there! Thanks for reporting the issue. I'm gonna look at it and post a new release.

**Comment by Franccisco** [comment]
After checking the error and trying your suggestions, I figured out that ```get_interpreter_for_subproccess``` has been added recently, and importing that function may conflict with Thonny installations whose versions are between 3.0.0 and the one ```get_interpreter_for_subproccess``` was added (especially from some Linux repositories). So, if it's ok for you, I'm gonna implement ```get_interpreter_for_subproccess``` directly in my code until Thonny gets uptaded from those repositories.

**Comment by aivarannamaa** [comment]
>  So, if it's ok for you, I'm gonna implement get_interpreter_for_subproccess directly in my code until Thonny gets uptaded from those repositories.

Good idea!
